To Do list: list structure
brenoxav/to-do-list pull request #1
Opened 2021-07-13 23:41 UTC by brenoxav

### To Do list: list structure

- Set up project with Webpack
- Create to-do list placeholder
- Create array with to-do tasks objects
- To-do tasks objects with properties:
  - description [string]
  - completed [bool]
  - index [number]
- Populate HTML with elements for each task
- Render tasks on page load

2021-07-13 23:55 UTC, mricanho requested changes
Hi @brenoxav, 

Good job so far! 🔥🔥 You have all the right JS code and the webpack configuration!

There are some issues that you still need to work on to go to the next project but you are almost there!

 ## Required Changes ♻️

- [x] For some reason I can't see your project on my browser, double-check the HTML and the JS code.

Your app:

![image](https://user-images.githubusercontent.com/60631456/125539763-2494f339-52f4-41a1-ac62-f2271e63ac42.png)

Target styling:

![image](https://user-images.githubusercontent.com/60631456/125539781-760e1f35-47c0-4c00-8cf7-719b54c01537.png)

- [ ] Add to your README file all the instructions to set up and run your app locally

_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-07-13 23:55 UTC, mricanho commented on README.md
>  ### Install
- [ ] Fill all this sections

2021-07-14 15:42 UTC, brenoxav commented
### Required changes done
- I updated the README with instructions on how to copy and open the project locally.

By following the README instructions, you should be able to open the project in your browser.

2021-07-14 16:25 UTC, hemant-soni-vst-au4 requested changes
Hi @brenoxav, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

![Alt Text](https://media.giphy.com/media/q6U4fbreC4Neo/giphy.gif)
 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers,
Hemant Soni
Cheers and happy coding 😃

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. You can mention me (@hemant-soni-vst-au4) so I can see your comments and respond.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-07-14 16:25 UTC, hemant-soni-vst-au4 commented on webpack.config.js
>    entry: {
- [ ] The 'mode' option has not been set, webpack will fall back to 'production' for this value. Set the 'mode' option to 'development' or 'production' to enable defaults for each environment.  Please try to fix this issue.

![image](https://user-images.githubusercontent.com/53019916/125656933-82a93d6f-e9d4-40b2-94d1-689c03cebf73.png)

2021-07-14 16:25 UTC, hemant-soni-vst-au4 commented on src/index.js
> +// }
- [ ]  Optional

- Please try to delete the commented lines in your code.

2021-07-14 16:49 UTC, brenoxav commented on src/index.js
> +// }
As this is an ongoing project, there are temporary comments.
In the final version of the project, there will be no unnecessary comments.

2021-07-14 16:52 UTC, brenoxav commented on webpack.config.js
>    entry: {
Since there are flags in the scripts, I didn't see the need to have *mode:'development'* in the config file.
But I did the requested change, anyway.

2021-07-14 17:03 UTC, smcommits approved these changes
### Status: Approved 👍🏽 

Hi @brenoxav, 

## You have done a great job! Your project is complete. This PR is now approved. You can go ahead and merge the branch. Congratulations! 🎉 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

2021-07-14 17:04 UTC, merged